packages:
    - 'packages/*'

catalog:
    # Svelte
    svelte: ^5.50.0
    '@sveltejs/vite-plugin-svelte': ^6.2.4

    # TypeScript & Build
    typescript: ^5.9.3
    vite: ^7.3.1
    vite-plugin-web-extension: ^4.4.1

    # React (time-tracker 호환 유지, 향후 Svelte 전환 시 제거)
    react: ^19.2.4
    react-dom: ^19.2.4
    '@vitejs/plugin-react': ^5.1.2
    '@types/react': ^19.2.10
    '@types/react-dom': ^19.2.3

    # vanilla-extract
    '@vanilla-extract/css': ^1.18.0
    '@vanilla-extract/vite-plugin': ^5.1.4

    # Linting & Formatting
    eslint: ^9.39.2
    '@eslint/js': ^9.39.2
    prettier: ^3.8.1
    typescript-eslint: ^8.54.0
    globals: ^17.2.0
    jiti: ^2.6.1
    eslint-config-prettier: ^10.1.8
    eslint-plugin-prettier: ^5.5.5
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.5.0
    eslint-plugin-svelte: ^3.14.0

    # Testing
    vitest: ^4.0.18
    '@vitest/coverage-v8': ^4.0.18
    '@vitest/ui': ^4.0.18
    '@testing-library/jest-dom': ^6.9.1
    '@testing-library/react': ^16.3.2
    '@testing-library/svelte': ^5.3.1
    '@testing-library/user-event': ^14.6.1
    jsdom: ^28.0.0

    # Storybook
    storybook: ^10.2.11
    '@storybook/svelte-vite': ^10.2.11
    '@storybook/addon-svelte-csf': ^5.0.11
    '@storybook/test': ^8.6.15

    # Documentation
    vitepress: ^1.6.4

    # Types
    '@types/node': ^25.0.10
    '@types/chrome': ^0.1.36
